# Generated by Django 5.0.6 on 2024-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='telegram_bot',
            field=models.URLField(default='https://t.me/diyorbek_backend'),
        ),
    ]
